/*
 * Copyright 2005-2006 UniVis Explorer development team.
 *
 * This file is part of UniVis Explorer
 * (http://phobos22.inf.uni-konstanz.de/univis).
 *
 * UniVis Explorer is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public License
 * as published by the Free Software Foundation; either version 2.1
 * of the License, or (at your option) any later version.
 *
 * Please see COPYING for the complete licence.
 */
package unikn.dbis.univis.exception;

import unikn.dbis.univis.util.ComponentUtilities;

import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
import java.awt.*;

/**
 * TODO: document me!!!
 * <p/>
 * <code>VDialog</code>.
 * <p/>
 * User: raedler, weiler
 * Date: 21.05.2006
 * Time: 00:13:24
 *
 * @author Roman R&auml;dle
 * @author Andreas Weiler
 * @version $Id: VDialog.java 338 2006-10-08 23:11:30Z raedler $
 * @since UniVis Explorer 0.1
 */
public class VDialog extends javax.swing.JDialog {

    private boolean detailsOpen = false;

    /** Creates new form VDialog */
    public VDialog(Frame owner, Exception e) {
        super(owner, true);
        initComponents(e);

        pack();
        setSize(500, (int) getSize().getHeight());

        ComponentUtilities.centerComponentOnScreen(this);

        setVisible(true);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">
    private void initComponents(Exception e) {
        java.awt.GridBagConstraints gridBagConstraints;

        details = new javax.swing.JButton();
        close = new javax.swing.JButton();
        save = new javax.swing.JButton();
        top = new javax.swing.JPanel();
        message = new javax.swing.JLabel();
        exceptionScroller = new javax.swing.JScrollPane();
        exception = new javax.swing.JTextArea();

        setLayout(new java.awt.GridBagLayout());

        details.setText("Details >>");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        add(details, gridBagConstraints);

        close.setText("Schlie\u00dfen");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        add(close, gridBagConstraints);

        save.setText("Speichern");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        add(save, gridBagConstraints);

        message.setText("Exception: " + e.getLocalizedMessage());

        org.jdesktop.layout.GroupLayout topLayout = new org.jdesktop.layout.GroupLayout(top);
        top.setLayout(topLayout);
        topLayout.setHorizontalGroup(
            topLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(topLayout.createSequentialGroup()
                .add(message)
                .addContainerGap(295, Short.MAX_VALUE))
        );
        topLayout.setVerticalGroup(
            topLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(topLayout.createSequentialGroup()
                .add(message)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        add(top, gridBagConstraints);

        exceptionScroller.setMinimumSize(new java.awt.Dimension(400, 300));
        exceptionScroller.setPreferredSize(new java.awt.Dimension(400, 300));

        StringBuilder builder = new StringBuilder();
        for (StackTraceElement element : e.getStackTrace()) {
            builder.append(element.toString()).append(System.getProperty("line.separator"));
        }
        exception.setText(builder.toString());
        exception.setCaretPosition(1);

        exception.setColumns(20);
        exception.setRows(5);
        exceptionScroller.setViewportView(exception);

        final GridBagConstraints gridBagConstraints2 = new java.awt.GridBagConstraints();
        gridBagConstraints2.gridx = 0;
        gridBagConstraints2.gridy = 2;
        gridBagConstraints2.gridwidth = 4;
        gridBagConstraints2.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints2.insets = new java.awt.Insets(4, 4, 4, 4);
        //add(exceptionScroller, gridBagConstraints2);

        details.addActionListener(new ActionListener() {
            /**
             * Invoked when an action occurs.
             */
            public void actionPerformed(ActionEvent e) {

                if (detailsOpen) {
                    remove(exceptionScroller);
                    detailsOpen = false;
                }
                else {
                    add(exceptionScroller, gridBagConstraints2);
                    detailsOpen = true;
                }

                validate();
                pack();
                repaint();
            }
        });

        close.addActionListener(new ActionListener() {
            /**
             * Invoked when an action occurs.
             */
            public void actionPerformed(ActionEvent e) {
                dispose();
            }
        });

    }// </editor-fold>

    public static void main(String[] args) {
        /*
        JFrame frame = new JFrame();
        frame.getContentPane().add(new VDialog());
        frame.pack();
        frame.setVisible(true);
        */

        /*
        VDialog dialog = new VDialog();
        dialog.pack();
        dialog.setVisible(true);
        */
    }

    // Variables declaration - do not modify
    private javax.swing.JButton close;
    private javax.swing.JButton details;
    private javax.swing.JTextArea exception;
    private javax.swing.JScrollPane exceptionScroller;
    private javax.swing.JLabel message;
    private javax.swing.JButton save;
    private javax.swing.JPanel top;
    // End of variables declaration

}