/*
 * VDialog.java
 *
 * Created on 24. Mai 2006, 16:16
 */

package unikn.dbis.univis.exception;

/**
 *
 * @author  Romsl
 */
public class VDialog extends javax.swing.JPanel {
    
    /** Creates new form VDialog */
    public VDialog() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        details = new javax.swing.JButton();
        close = new javax.swing.JButton();
        save = new javax.swing.JButton();
        top = new javax.swing.JPanel();
        message = new javax.swing.JLabel();
        exceptionScroller = new javax.swing.JScrollPane();
        excepion = new javax.swing.JTextArea();

        setLayout(new java.awt.GridBagLayout());

        details.setText("Details >>");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        add(details, gridBagConstraints);

        close.setText("Schlie\u00dfen");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        add(close, gridBagConstraints);

        save.setText("Speichern");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        add(save, gridBagConstraints);

        message.setText("Exception: FooBarBaz");

        org.jdesktop.layout.GroupLayout topLayout = new org.jdesktop.layout.GroupLayout(top);
        top.setLayout(topLayout);
        topLayout.setHorizontalGroup(
            topLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(topLayout.createSequentialGroup()
                .add(message)
                .addContainerGap(295, Short.MAX_VALUE))
        );
        topLayout.setVerticalGroup(
            topLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(topLayout.createSequentialGroup()
                .add(message)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        add(top, gridBagConstraints);

        exceptionScroller.setMinimumSize(new java.awt.Dimension(400, 300));
        exceptionScroller.setPreferredSize(new java.awt.Dimension(400, 300));
        excepion.setColumns(20);
        excepion.setRows(5);
        excepion.setPreferredSize(new java.awt.Dimension(400, 300));
        exceptionScroller.setViewportView(excepion);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        add(exceptionScroller, gridBagConstraints);

    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton close;
    private javax.swing.JButton details;
    private javax.swing.JTextArea excepion;
    private javax.swing.JScrollPane exceptionScroller;
    private javax.swing.JLabel message;
    private javax.swing.JButton save;
    private javax.swing.JPanel top;
    // End of variables declaration//GEN-END:variables
    
}
