/*
 * VExceptionDialog.java
 *
 * Created on 21. Mai 2006, 01:29
 */

package unikn.dbis.univis.exception;

/**
 *
 * @author  Romsl
 */
public class VExceptionDialog extends javax.swing.JPanel {
    
    /** Creates new form VExceptionDialog */
    public VExceptionDialog() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        label = new javax.swing.JLabel();
        close = new javax.swing.JButton();
        openDetails = new javax.swing.JButton();
        scrollPane = new javax.swing.JScrollPane();
        exceptionArea = new javax.swing.JTextArea();

        label.setText("jLabel1");

        close.setText("Schlie\u00dfen");

        openDetails.setText("<< Details");

        exceptionArea.setColumns(20);
        exceptionArea.setRows(5);
        scrollPane.setViewportView(exceptionArea);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(label)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .add(openDetails)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(close))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, scrollPane, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(label)
                .add(44, 44, 44)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(close)
                    .add(openDetails))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(scrollPane, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton close;
    private javax.swing.JTextArea exceptionArea;
    private javax.swing.JLabel label;
    private javax.swing.JButton openDetails;
    private javax.swing.JScrollPane scrollPane;
    // End of variables declaration//GEN-END:variables
    
}
